import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar"; // Default import
import { Toaster } from "@/components/ui/toaster";
import Provider from "@/components/Provider";
import { authOptions } from "@/lib/auth";
import { getServerSession } from "next-auth";
import { Session } from "next-auth"; // For session typing

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dream Interpreter App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let session: Session | null = null;

  try {
    session = await getServerSession(authOptions);
  } catch (error) {
    console.error("Failed to fetch session:", error);
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Navbar session={session} />
          <main>{children}</main>
          <Toaster />
        </Provider>
      </body>
    </html>
  );
}
